language: ruby

rvm:
  - 3.2.2

env:
  - DB=sqlite3
  - DB=postgresql

gemfile:
  - gemfiles/activerecord_7.0.gemfile

sudo: false

bundler_args: '--without local_development --jobs 3 --retry 3'

script: bundle exec rake

matrix:
  fast_finish: true
  allow_failures:
      - gemfile: gemfiles/activerecord_7.0.gemfile
      - rvm: 3.2.2
